sudo: required
services:
  - docker

before_install:
  docker build -t jeffkatzy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jeffkatzy/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-815414769568"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

